import {build} from 'esbuild';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
const fixture=process.env.PREVIEW_FIXTURE?JSON.parse(await readFile(process.env.PREVIEW_FIXTURE,'utf8')):null;
const bundle=await build({entryPoints:[new URL('../ui/page.tsx',import.meta.url).pathname],bundle:true,write:false,define:{'process.env.NODE_ENV':'"development"'}});
const sample=fixture?.status??{connected:true,cookie:123,master:{id:73,serial:173,app:"系统总音量",binary:"",pid:null,name:"Built-in Audio Playback",state:"running",system:true,volume:41,muted:false,error:null},streams:[
{id:100,serial:1000,app:'SteamVR',binary:'vrserver',pid:2616,name:'Streaming audio',state:'running',system:false,volume:75,muted:false,error:null},
{id:101,serial:1001,app:'Firefox',binary:'firefox',pid:8301,name:'Music',state:'running',system:false,volume:40,muted:false,error:null},
{id:102,serial:1002,app:'Firefox',binary:'firefox',pid:8301,name:'Video',state:'idle',system:false,volume:60,muted:false,error:null},
{id:103,serial:1003,app:'Discord',binary:'discord',pid:4500,name:'Voice chat',state:'idle',system:false,volume:100,muted:true,error:null},
],error:null};
sample.outputs??=[sample.master].filter(Boolean);
for(const s of sample.streams){s.userMuted??=s.muted;s.focused??=s.app==='Firefox';s.focusSupported??=true;}

const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>音量合成器 · 模拟预览</title><div id="root"></div><script>const sample=${JSON.stringify(sample)};const iconSamples=${JSON.stringify(fixture?.icons??{})};const listeners=new Set();function applyBackgroundMute(){for(const s of sample.streams){s.autoMuted=!!((sample.backgroundMute||s.backgroundMute)&&s.focused===false);s.muted=!!(s.userMuted||s.autoMuted)}}window.__framelyBridge={subscribe:f=>{listeners.add(f);return()=>listeners.delete(f)},request:async(op,p)=>{const delayed=new URLSearchParams(location.search).has('lag');if(op==='language.get')return {preference:'auto',language:new URLSearchParams(location.search).get('hostLanguage')??'zh-CN'};if(p?.method==='icon.get')return iconSamples[p.params.key]??{src:null};if(op==='window.open'){location.href='/main';return}if(p.method==='focus.global'){sample.backgroundMute=p.params.enabled;applyBackgroundMute();return structuredClone(sample)}if(p.method==='focus.set'){for(const s of sample.streams.filter(s=>s.pid===sample.streams.find(s=>s.serial===p.params.target.serial)?.pid))s.backgroundMute=p.params.enabled;applyBackgroundMute();return structuredClone(sample)}if(p.method==='outputs.default'){sample.master=sample.outputs.find(s=>s.serial===p.params.target.serial)??sample.master;return structuredClone(sample)}if(p.method==='streams.set'||p.method==='master.set'||p.method==='outputs.set'){const previous=structuredClone(sample);if(delayed)await new Promise(r=>setTimeout(r,100));const update=()=>{for(const t of p.params.targets){const s=[sample.master,...sample.streams,...sample.outputs].find(s=>s.serial===t.serial);if(p.params.volume!==undefined)s.volume=p.params.volume;if(p.params.muted!==undefined){s.muted=p.params.muted;if(sample.streams.includes(s))s.userMuted=p.params.muted;}const output=sample.outputs.find(s=>s.serial===t.serial);if(output){if(p.params.volume!==undefined)output.volume=p.params.volume;if(p.params.muted!==undefined)output.muted=p.params.muted}}applyBackgroundMute()};if(delayed){setTimeout(update,500);return previous}update()}return structuredClone(sample)}};const nextLanguage=new URLSearchParams(location.search).get('hostLanguageAfter');if(nextLanguage)setTimeout(()=>listeners.forEach(f=>f({type:'language.changed',data:{preference:'auto',language:nextLanguage}})),2500);setInterval(()=>listeners.forEach(f=>f({type:'status',data:structuredClone(sample)})),new URLSearchParams(location.search).has('lag')?100:500);</script><script src="/page.js"></script></html>`;
createServer((req,res)=>{res.setHeader('Content-Type',req.url==='/page.js'?'application/javascript':'text/html; charset=utf-8');res.end(req.url==='/page.js'?bundle.outputFiles[0].contents:req.url==='/host'?'<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Framely 容器预览</title><style>html,body{margin:0;height:100%;background:#17191c}iframe{display:block;width:100%;height:100%;border:0}</style><iframe title="Volume mixer" src="/main?hostLanguage=zh-CN"></iframe></html>':html)}).listen(Number(process.env.PORT??4319),'127.0.0.1',()=>console.log(`模拟预览 http://127.0.0.1:${process.env.PORT??4319}/main 或 /quick`));
